# Site/SEO settings
email: me@rileymccullagh.com
baseurl: ""
permalink: /:title/
google_analytics: 

name: Riley McCullagh
title: Riley McCullagh 
description: >
    Riley McCullagh is a composer and sound designer from Sydney
url: http://rileymccullagh.com
twitter_username: 
default_img: /assets/images/seo.jpg
social:

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/eBfSBGyMBZ1u

# Disqus settings
disqus: 

# MailChimp settings

# Author settings
author:
  - name: Riley McCullagh 
    bio: 
    url: 

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
